export const GET_BREEDS = 'LOAD_BREEDS';
export const GET_BREEDS_SUCCESS = 'LOAD_BREEDS_SUCCESS';
export const GET_BREEDS_FAIL = 'LOAD_BREEDS_FAIL';

export const GET_SUB_BREEDS = 'LOAD_SUB_BREEDS';
export const GET_SUB_BREEDS_SUCCESS = 'LOAD_SUB_BREEDS_SUCCESS';
export const GET_SUB_BREEDS_FAIL = 'LOAD_SUB_BREEDS_FAIL';

export const GET_RANDOM_IMAGE = 'LOAD_IMAGE';
export const GET_RANDOM_IMAGE_SUCCESS = 'LOAD_IMAGE_SUCCESS';
export const GET_RANDOM_IMAGE_FAIL = 'LOAD_IMAGE_FAIL';

export const SET_SEARCH_TEXT = 'SET_SEARCH_TEXT';
export const SEARCH_BREEDS = 'SEARCH_BREEDS';
